#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xdefaults &
# xscreensaver -no-splash &
feh --bg-scale ~/Pictures/chilewaterfall.jpg &

# Automatically mount removable media
thunar --daemon &

# Get us some decent gtk themes going
gnome-settings-daemon &

# Start the system tray
tray &

# Start network manage applet
nm-applet &


# Start a terminal
# urxvt &
gnome-terminal &

# Start browsers
# chromium &
firefox &

# Start some muther flippin chat client
#empathy &

# Start xchat (IRC client)
# xchat &

exec ck-launch-session dbus-launch --sh-syntax --exit-with-session xmonad
