#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xdefaults &
# xscreensaver -no-splash &
feh --bg-scale ~/Pictures/chilewaterfall.jpg &

# Automatically mount removable media
#thunar --daemon &

# Start network manage applet
nm-applet &
bluetooth-applet &

# Start a terminal
gnome-terminal &

# Start some muther flippin chat client
empathy &

# Start browsers
# chromium &
firefox &

# Start xchat (IRC client)
# xchat &
#gnome-session &

# Seems this is needed to start the battery indicator in trayer
gnome-settings-daemon &

# Start the system tray
~/.xmonad/bin/tray &

exec ssh-agent dbus-launch --sh-syntax --exit-with-session xmonad
