#!/usr/bin/env bash
#
# checks pacman and AUR for updates. 

available=0
checkupdates="/usr/bin/checkupdates"
auracle="/usr/bin/auracle"

available=$(($($checkupdates | wc -l) + $($auracle sync | wc -l)))

if [ $available != 0 ]; then
   echo "   $available Updates"
else
   echo
fi
