#!/usr/bin/env bash

connections=`bluetoothctl paired-devices`
mac=`echo $connections | awk '{print $2}'`
name=`echo $connections | awk '{print $3}'`
connected=`bluetoothctl info $mac | grep Connected | awk '{print $2}'`
if [ "$connected" == "yes" ]; then
   echo $name
else
   echo
fi
