#!/bin/bash

percent=`acpi -b | awk '{print $4}' | sed 's/[^0-9]*//g' | awk '{s+=$1} END {print int((s+1)/2)}'`

full_text="$percent%"
if [ $percent -lt 20 ]; then
    color="#FF0000\n"
    icon=""
elif [ $percent -lt 40 ]; then
    color="#FFAE00\n"
    icon=""
elif [ $percent -lt 60 ]; then
    color="#FFF600\n"
    icon=""
elif [ $percent -lt 85 ]; then
    color="#A8FF00\n"
    icon=""
else
    color="#A8FF00\n"
    icon="" 
fi

echo "$icon $full_text"
echo "$full_text"
echo "$color"
