#!/bin/bash

percent=`acpi -b | awk '{print $4}' | sed 's/[^0-9]*//g' | awk '{s+=$1} END {print int((s+1)/2)}'`

full_text="$percent%"
if [ $percent -lt 20 ]; then
    color="#DC322F\n"
    icon=""
elif [ $percent -lt 40 ]; then
    color="#CB4B16\n"
    icon=""
elif [ $percent -lt 60 ]; then
    color="#B58900\n"
    icon=""
elif [ $percent -lt 85 ]; then
    color="#83AF40\n"
    icon=""
else
    color="#83AF40\n"
    icon="" 
fi

echo "$icon $full_text"
echo "$full_text"
echo "$color"
